enum AuthResponseCode {
  E_FORBIDEN_ROLE = 'E_FORBIDEN_ROLE',
  E_MISSING_CREDENTIALS = 'E_MISSING_CREDENTIALS',
  E_UNAUTHORIZED = 'E_UNAUTHORIZED',
  E_AUTH_UNAUTHORIZED = 'E_AUTH_UNAUTHORIZED',
  E_INVALID_CREDENTIALS = 'E_INVALID_CREDENTIALS',
  E_FORBIDEN = 'E_FORBIDEN',
  E_EMAIL_ALREADY_VERIFIED = 'E_EMAIL_ALREADY_VERIFIED',
  E_EXPIRED_TOKEN = 'E_EXPIRED_TOKEN',
  E_REFRESH_TOKEN_EXPIRED = 'E_REFRESH_TOKEN_EXPIRED',
  E_ACCESS_TOKEN_EXPIRED = 'E_ACCESS_TOKEN_EXPIRED',
  E_OTP_INVALID = 'E_OTP_INVALID',
  E_OTP_EXPIRED = 'E_OTP_EXPIRED',
}

export default AuthResponseCode;
